apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temperalio-fib-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ingressClassName: traefik
  rules:
    - host: kind.neo.nsstc.uah.edu
      http:
        paths:
          - backend:
              service:
                name: temporal-fib-api
                port:
                  number: 80
            path: /api/predict/v1/fib
            pathType: Prefix
