apiVersion: v1
kind: Service
metadata:
  name: temporal-fib-api
spec:
  selector:
    app: temporal-fibo-worker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
  